In [1]:
import pandas as pd

In [2]:
df_reviews = pd.read_csv("hotel_reviews.csv")
df_info = pd.read_csv("hotel_info.csv")

display(df_reviews)
display(df_info)

,hotel_name,hotel_location,review_title,review_pos,review_neg,review_date,review_country,num_reviews_by_reviewer,reviewer_name,review_rating,review_tags,sentiment
0,Siam Eco Hostel,"13.75308373,100.53145603",“Nice hostel in a great location”,"it’s really well located, the stuff is nice an...","the breakfast could be better, but I guess it’...",2022-04-2T00:00:00,Germany,15,Karina,9.0,"Leisure trip,Solo traveller,Bed in 6-Bed Femal...",1
1,Siam Eco Hostel,"13.75308373,100.53145603",“Relaxed hostel with great staff and great com...,The staff was superfriendly and helpful and th...,Don't expect too much from the provided breakf...,2022-03-31T00:00:00,Netherlands,4,Pleun,9.0,"Leisure trip,Group,Bed in 6-Bed Mixed Dormitor...",1
2,Siam Eco Hostel,"13.75308373,100.53145603",“Great hostel in convenient location”,"really nice reception staff, who let us check ...","Breakfast was a little small, but was fine",2022-03-6T00:00:00,United Kingdom,7,Maia,10.0,"Leisure trip,Group,Economy Quadruple Room with...",1
3,Siam Eco Hostel,"13.75308373,100.53145603",Exceptional,"Clean, nice and calm space. Breakfast was some...",No Negative,2022-03-1T00:00:00,Norway,1,Emmeli,10.0,"Leisure trip,Solo traveller,Bed in 6-Bed Femal...",1
4,Siam Eco Hostel,"13.75308373,100.53145603",“perfect place”,everything is perfect: women in reception so n...,No Negative,2022-02-24T00:00:00,Lithuania,76,Sooofija,10.0,"Leisure trip,Solo traveller,Bed in 6-Bed Femal...",1
...,...,...,...,...,...,...,...,...,...,...,...,...
142291,ZEN Rooms Bukit Merah,"1.27264209,103.82767699",Poor,No Positive,No Negative,2019-06-4T00:00:00,South Korea,1,Hasung,3.3,"Business trip,Solo traveller,Superior Twin Roo...",0
142292,Seaside Glamping@Heritage Chalet,"1.38639530,103.94169860",Pleasant,The tenant lady is helpful accomodating my req...,The music at the fish pond during all night an...,2022-02-28T00:00:00,Singapore,8,Geraldine,6.0,"Leisure trip,Family with young children,Chalet...",1
142293,Seaside Glamping@Heritage Chalet,"1.38639530,103.94169860",Poor,"Place is big and roomy, near the sea and other...",Poorly maintained and dirty. No formal checkin...,2022-03-15T00:00:00,Singapore,1,Chun,3.0,"Business trip,Solo traveller,Chalet with Sea V...",0
142294,Seaside Glamping@Heritage Chalet,"1.38639530,103.94169860",Very poor,Winston was a helpful housekeeping ..even help...,A1 unit Haunted room of masterbedroom n room 3...,2022-01-24T00:00:00,Singapore,1,Nor,2.0,"Leisure trip,Family with young children,Chalet...",0
142295,Seaside Glamping@Heritage Chalet,"1.38639530,103.94169860",Poor,No Positive,No Negative,2022-03-28T00:00:00,Singapore,1,Dominique,3.0,"Leisure trip,Couple,Superior Tent,Stayed 1 nig...",0

,hotel_name,hotel_address,hotel_location,hotel_rating,hotel_description,hotel_country,hotel_num_reviews,unique_tags,hotel_img_url,hotel_link
0,Siam Eco Hostel,"486/106-107 Petchaburi Road, Thanon Petchaburi...","13.75308373,100.53145603",9.9,You're eligible for a Genius discount at Siam ...,Thailand,367,"Economy Quadruple Room with Shared Bathroom,St...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/th/siam-eco-host...
1,Tiny Taladnoi Hostel,"80-82 Yotha Road, Talat Noi, Samphanthawong, 1...","13.73197965,100.51380123",9.9,You're eligible for a Genius discount at Tiny ...,Thailand,225,"Stayed 4 nights,Bed in 6-Bed Mixed Dormitory R...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/th/tiny-taladnoi...
2,Rich8 Hostel,102 Soi Wora Phong (สามเสน6) ถนนวิสุทธิกษัตริย...,"13.76338800,100.50243400",9.7,You're eligible for a Genius discount at Rich8...,Thailand,482,"Stayed 4 nights,Classic Quadruple Room,Submitt...",https://cf.bstatic.com/xdata/images/hotel/max5...,https://www.booking.com/hotel/th/rich8-hostel....
3,Kinnon Deluxe Hostel Coworking Cafe,"39/22-24 Silom Soi 6 Silom Road, Suriyawong, B...","13.72826150,100.52962729",10.0,You're eligible for a Genius discount at Kinno...,Thailand,560,"4-Bed Mixed Dormitory Room,Stayed 4 nights,Bed...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/th/kinnon-hostel...
4,Tamni,"476/4-5 Soi Phraya Sinhaseni Rama 4 Rd, Rongmu...","13.73839866,100.51781600",9.7,"Located in Bangkok, 0.9 miles from MBK Center,...",Thailand,64,"Small Double Room,Bed in 4-Bed Mixed Dormitory...",https://cf.bstatic.com/xdata/images/hotel/max5...,https://www.booking.com/hotel/th/tamni.en-gb.h...
...,...,...,...,...,...,...,...,...,...,...
1925,New Orchid Hotel (SG Clean),"347 Balestier Road,, Novena, 329777 Singapore,...","1.32426130,103.85121980",6.7,New Orchid Hotel has air-conditioned rooms wit...,Singapore,71,"Submitted via mobile,Stayed 1 night,Stayed 3 n...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/sg/new-orchid.en...
1926,Deluxe Studio & Suite by Recharge,"293 River Valley Road, 238334 Singapore, Singa...","1.29573510,103.83959950",10.0,"Boasting a terrace and free WiFi, Deluxe Studi...",Singapore,14,"Submitted via mobile,Stayed 1 night,Standard T...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/sg/deluxe-studio...
1927,Meadows Hostel,"7A Hamilton Road, Lavender, 209178 Singapore, ...","1.31120679,103.86052430",7.5,Capsule-style single or double beds in dormito...,Singapore,12,"Submitted via mobile,Stayed 3 nights,Stayed 1 ...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/sg/abc-hostel-ha...
1928,ZEN Rooms Bukit Merah,"Located in Harbour Ville Hotel, 512 Kampong Ba...","1.27264209,103.82767699",6.5,ZenRooms Bukit Merah offers accommodation in S...,Singapore,5,"Submitted via mobile,Stayed 1 night,Stayed 5 n...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/sg/zenrooms-buki...
1929,Seaside Glamping@Heritage Chalet,"125a Pasir Ris Road, 519121 Singapore, Singapore","1.38639530,103.94169860",7.5,"Featuring a restaurant, a garden as well as ba...",Singapore,6,"Chalet with Garden View,Submitted via mobile,S...",https://cf.bstatic.com/xdata/images/hotel/max5...,https://www.booking.com/hotel/sg/seaside-glamp...

In [3]:
df_reviews['hotel_name'].nunique()

1922

In [4]:
df_reviews['sentiment_pos'] = df_reviews['sentiment'].apply(lambda x: 1 if x == 1 else 0)
df_reviews['sentiment_neg'] = df_reviews['sentiment'].apply(lambda x: 1 if x == 0 else 0)

display(df_reviews)

,hotel_name,hotel_location,review_title,review_pos,review_neg,review_date,review_country,num_reviews_by_reviewer,reviewer_name,review_rating,review_tags,sentiment,sentiment_pos,sentiment_neg
0,Siam Eco Hostel,"13.75308373,100.53145603",“Nice hostel in a great location”,"it’s really well located, the stuff is nice an...","the breakfast could be better, but I guess it’...",2022-04-2T00:00:00,Germany,15,Karina,9.0,"Leisure trip,Solo traveller,Bed in 6-Bed Femal...",1,1,0
1,Siam Eco Hostel,"13.75308373,100.53145603",“Relaxed hostel with great staff and great com...,The staff was superfriendly and helpful and th...,Don't expect too much from the provided breakf...,2022-03-31T00:00:00,Netherlands,4,Pleun,9.0,"Leisure trip,Group,Bed in 6-Bed Mixed Dormitor...",1,1,0
2,Siam Eco Hostel,"13.75308373,100.53145603",“Great hostel in convenient location”,"really nice reception staff, who let us check ...","Breakfast was a little small, but was fine",2022-03-6T00:00:00,United Kingdom,7,Maia,10.0,"Leisure trip,Group,Economy Quadruple Room with...",1,1,0
3,Siam Eco Hostel,"13.75308373,100.53145603",Exceptional,"Clean, nice and calm space. Breakfast was some...",No Negative,2022-03-1T00:00:00,Norway,1,Emmeli,10.0,"Leisure trip,Solo traveller,Bed in 6-Bed Femal...",1,1,0
4,Siam Eco Hostel,"13.75308373,100.53145603",“perfect place”,everything is perfect: women in reception so n...,No Negative,2022-02-24T00:00:00,Lithuania,76,Sooofija,10.0,"Leisure trip,Solo traveller,Bed in 6-Bed Femal...",1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142291,ZEN Rooms Bukit Merah,"1.27264209,103.82767699",Poor,No Positive,No Negative,2019-06-4T00:00:00,South Korea,1,Hasung,3.3,"Business trip,Solo traveller,Superior Twin Roo...",0,0,1
142292,Seaside Glamping@Heritage Chalet,"1.38639530,103.94169860",Pleasant,The tenant lady is helpful accomodating my req...,The music at the fish pond during all night an...,2022-02-28T00:00:00,Singapore,8,Geraldine,6.0,"Leisure trip,Family with young children,Chalet...",1,1,0
142293,Seaside Glamping@Heritage Chalet,"1.38639530,103.94169860",Poor,"Place is big and roomy, near the sea and other...",Poorly maintained and dirty. No formal checkin...,2022-03-15T00:00:00,Singapore,1,Chun,3.0,"Business trip,Solo traveller,Chalet with Sea V...",0,0,1
142294,Seaside Glamping@Heritage Chalet,"1.38639530,103.94169860",Very poor,Winston was a helpful housekeeping ..even help...,A1 unit Haunted room of masterbedroom n room 3...,2022-01-24T00:00:00,Singapore,1,Nor,2.0,"Leisure trip,Family with young children,Chalet...",0,0,1
142295,Seaside Glamping@Heritage Chalet,"1.38639530,103.94169860",Poor,No Positive,No Negative,2022-03-28T00:00:00,Singapore,1,Dominique,3.0,"Leisure trip,Couple,Superior Tent,Stayed 1 nig...",0,0,1

In [5]:
df_count = df_reviews.groupby("hotel_name").sum().reset_index()[['hotel_name', 'sentiment_pos','sentiment_neg']].rename(columns={'sentiment_pos':'num_of_pos', 'sentiment_neg':'num_of_neg'})

display(df_count)

                                           hotel_name  num_of_pos  num_of_neg
0                           &AND HOSTEL HOMMACHI EAST          94           1
1                                      04village Kujo          12           0
2                                     04village Namba          37           3
3                                 103 - Bed and Brews          41           1
4                       130 Hotel & Residence Bangkok          47           1
...                                               ...         ...         ...
1917  voco Orchard Singapore - SG Clean, an IHG Hotel          15           5
1918                          wawa residence รัชดา 36           2           0
1919           โรงแรมมิ้นท์เทล หัวหมาก Mintel Huamark           8           0
1920                              ゲストハウス888 女性専用ドミトリー           8           0
1921                             大阪鶴橋亭ホテル Asahi group           1           0

[1922 rows x 3 columns]

In [6]:
df_merged = df_count.merge(df_info)

display(df_merged)

,hotel_name,num_of_pos,num_of_neg,hotel_address,hotel_location,hotel_rating,hotel_description,hotel_country,hotel_num_reviews,unique_tags,hotel_img_url,hotel_link
0,&AND HOSTEL HOMMACHI EAST,94,1,"540-0028 Osaka Prefecture, Osaka, Chuo-ku Toki...","34.68214100,135.51200700",8.8,You're eligible for a Genius discount at &AND ...,Japan,1434,"Stayed 4 nights,Quadruple Room with Shared Bat...",https://cf.bstatic.com/xdata/images/hotel/max5...,https://www.booking.com/hotel/jp/amp-and-hoste...
1,04village Kujo,12,0,"550-0025 Osaka Prefecture, Osaka, Nishi-ku Kuj...","34.67190315,135.47253635",9.2,You're eligible for a Genius discount at 04vil...,Japan,153,"Submitted via mobile,Stayed 1 night,Stayed 3 n...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/jp/04village-kuj...
2,04village Namba,37,3,"556-0001 Osaka Prefecture, Osaka, Naniwa-ku Sh...","34.65499047,135.50847843",9.3,You're eligible for a Genius discount at 04vil...,Japan,373,"8-Bed Female Dormitory Room,Stayed 4 nights,Fa...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/jp/04village-nam...
3,103 - Bed and Brews,41,1,"103 Soi Nana (chinatown) Rama IV Road, Pom Pra...","13.73924929,100.51393934",8.8,103 - Bed and Brews is set in the Bangkok Old ...,Thailand,270,"Standard Suite,Submitted via mobile,Stayed 1 n...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/th/103-bed-and-b...
4,130 Hotel & Residence Bangkok,47,1,"25 Lat Phrao soi 130 Khlong chan, Bang Kapi, 1...","13.77177104,100.63207457",8.8,You're eligible for a Genius discount at 130 H...,Thailand,354,"Stayed 7 nights,Deluxe Double Room,Stayed 3 ni...",https://cf.bstatic.com/xdata/images/hotel/max5...,https://www.booking.com/hotel/th/130-amp-resid...
...,...,...,...,...,...,...,...,...,...,...,...,...
1918,"voco Orchard Singapore - SG Clean, an IHG Hotel",15,5,"581 Orchard Road, Orchard, 238883 Singapore, S...","1.30632108,103.82925779",8.8,You're eligible for a Genius discount at voco ...,Singapore,45,"Stayed 4 nights,Submitted via mobile,Stayed 1 ...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/sg/voco-orchard-...
1919,wawa residence รัชดา 36,2,0,191 Soi Ratchadaphisek 36 Yaek 9-15 เขตจตุจักร...,"13.82196802,100.58484065",8.7,"Situated in Bangkok, within 3.1 miles of Centr...",Thailand,22,"Submitted via mobile,Stayed 1 night,Solo trave...",https://cf.bstatic.com/xdata/images/hotel/max5...,https://www.booking.com/hotel/th/wawa-residenc...
1920,โรงแรมมิ้นท์เทล หัวหมาก Mintel Huamark,8,0,"17/3 Hua Mak Road, Bang Kapi, Bangkapi, 10240 ...","13.75177200,100.63841500",10.0,"Set in Bangkok, 3.7 miles from Central Festiva...",Thailand,40,"Submitted via mobile,Stayed 1 night,Stayed 3 n...",https://cf.bstatic.com/xdata/images/hotel/max5...,https://www.booking.com/hotel/th/mintel.en-gb....
1921,ゲストハウス888 女性専用ドミトリー,8,0,"530-0027 Osaka Prefecture, Osaka, 北区堂山町16-12, ...","34.70410700,135.50266300",9.1,"Offering free WiFi throughout the property, ゲス...",Japan,132,"Submitted via mobile,Stayed 3 nights,Stayed 1 ...",https://t-cf.bstatic.com/xdata/images/hotel/ma...,https://www.booking.com/hotel/jp/gesutohausu88...
1922,大阪鶴橋亭ホテル Asahi group,1,0,"544-0031 Osaka Prefecture, Osaka, Ikuno-ku Tsu...","34.66471818,135.53417775",8.5,You're eligible for a Genius discount at 大阪鶴橋亭...,Japan,43,"Family with young children,Leisure trip,Triple...",https://cf.bstatic.com/xdata/images/hotel/max5...,https://www.booking.com/hotel/jp/tsuruhashi-ho...

In [7]:
df_merged.describe()

        num_of_pos   num_of_neg  hotel_rating  hotel_num_reviews
count  1923.000000  1923.000000   1923.000000        1923.000000
mean     68.068643     5.952158      8.877431         529.807592
std      99.074660    10.733979      0.621887         736.528287
min       0.000000     0.000000      6.400000           5.000000
25%      18.000000     1.000000      8.500000         109.000000
50%      39.000000     3.000000      8.900000         288.000000
75%      82.500000     6.000000      9.300000         665.500000
max    1443.000000   194.000000     10.000000       12890.000000

In [8]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1923 entries, 0 to 1922
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   hotel_name         1923 non-null   object
 1   num_of_pos         1923 non-null   int64
 2   num_of_neg         1923 non-null   int64
 3   hotel_address      1923 non-null   object
 4   hotel_location     1923 non-null   object
 5   hotel_rating       1923 non-null   float64
 6   hotel_description  1923 non-null   object
 7   hotel_country      1923 non-null   object
 8   hotel_num_reviews  1923 non-null   int64
 9   unique_tags        1922 non-null   object
 10  hotel_img_url      1923 non-null   object
 11  hotel_link         1923 non-null   object
dtypes: float64(1), int64(3), object(8)
memory usage: 195.3+ KB

In [9]:
df_merged.to_csv('hotel_info(1).csv', index=False)